name: Deploy AGCM to Heroku

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: "Deployment to Heroku"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup GO
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: create env file
        env:
          PORT: ${{ secrets.APP_PORT }}
          DB_USERNAME: ${{ secrets.APP_DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.APP_DB_PASSWORD }}
          DB_HOST: ${{ secrets.APP_DB_HOST }}
          DB_PORT: ${{ secrets.APP_DB_PORT }}
          DB_NAME: ${{ secrets.APP_DB_NAME }}
          SECRET_JWT: ${{ secrets.APP_SECRET_JWT }}
        run: |
          touch .env
          echo PORT=$PORT >> .env
          echo DB_USERNAME=$DB_USERNAME >> .env
          echo DB_PASSWORD=$DB_PASSWORD >> .env
          echo DB_HOST=$DB_HOST >> .env
          echo DB_PORT=$DB_PORT >> .env
          echo DB_NAME=$DB_NAME >> .env
          echo SECRET_JWT=$SECRET_JWT >> .env
          ls /home/runner

      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: 'docker/go'
          process_type: 'web'